### ISSUE TITLE
Index out of range when running copypasta_reddit.py

### ISSUE THREAD

**Issue by CaptainMorgs** [louisabraham/copypasta-data#1]
Index out of range when running copypasta_reddit.py:

λ copypasta_reddit.py -1 > reddit3.txt
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "F:\Dev\Git\copypasta-data\copypasta_reddit.py", line 82, in <module>
    for p in handle_page(pool, soup):
  File "F:\Dev\Git\copypasta-data\copypasta_reddit.py", line 63, in handle_page
    elements = soup.select('#siteTable')[0]
IndexError: list index out of range

**Comment by louisabraham** [comment]
Hi, it should work now :)

Basically, reddit changed their interface but the old one is still available at https://old.reddit.com/. Maybe I should instead handle their new interface but it was faster to switch to the old one.

I'm surprised people even find this repo…

**Comment by CaptainMorgs** [comment]
I'm doing some copypasta stuff and this repo was helpful <3

**Comment by louisabraham** [comment]
I see you are a man of culture as well.

Don't hesitate if you need further help. Also, the reddit code works to scrape any subreddit.
